### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by yaklamtse** [aclew/DiViMe#1]
Dear reader,

I tried to install the software and entered vagrant up already several times, but I was not able to install the software. Along the post a screenshot of my screen.  I followed all steps and downloaded Vagrant and VirtualBox. Somebody knows what went wrong? Thanks! 
![vagrant_time_out](https://user-images.githubusercontent.com/37499299/37567718-28e2f538-2acb-11e8-8c9c-628c7a027d9e.png)
![connection_fail_vagrant](https://user-images.githubusercontent.com/37499299/37567719-2900d788-2acb-11e8-82fb-a2d4add2754d.png)

![installing_divime](https://user-images.githubusercontent.com/37499299/37567668-6df0296c-2aca-11e8-9f58-f4b65a484cc5.PNG)

**Comment by alecristia** [comment]
Hi yaklamtse ,

Thanks a lot for the bug report! I'm not sure about the timeout issue, or the missing error for eesen. I've added two people who may be able to help. 

For the "vagrant ssh -c "tools/test.sh", that feature is not implemented yet - my apologies! I'll keep you posted when it is.

-a

**Comment by jukaradayi** [comment]
Hi yaklamtse, 

Thank you for your feedback.
The first problem you pointed at (the first screenshot with "connection timed out") is a problem I already encountered but that seems to come directly from virtualbox. Which version of VirtualBox are you using? Which version of windows are you using ?
Could you try doing  `vagrant destroy` and `vagrant up` again ? Does the issue happen again ? If no, then could you try again with `vagrant ssh -c "tools/test.sh" ? 
For the second problem you pointed at, it doesn't find anything indeed because the Virtual Machine creation failed at the beginning so it didn't install any of the softwares at all.

Julien

**Comment by yaklamtse** [comment]
Hi Julien,
I tried several times using the destroy command and vagrant up, but it is still not working and giving me different output when running it 
![vagrant up](https://user-images.githubusercontent.com/37499299/37656532-95d83058-2c48-11e8-8efe-d40c88852875.PNG)
![power_shell](https://user-images.githubusercontent.com/37499299/37656546-a39d7ef0-2c48-11e8-8237-dc1eb2c68a9c.PNG)  If I am correct I do have the Powershell 3

I have Windows 8 and the VirtualBox 5.2.8 via the linked provided.

Thanks in advance,
Yaklam

**Comment by riebling** [comment]
I can't speak to the Powershell issue, but the vagrant up output indicates that a previous VM has been created by 'vagrant up' and so it does not run the provisioning script, except for the "always run" portion, which assumes provisioning has completed and therefore assumes /home/vagrant/tools... exists. It then throws an error because it does NOT exist. To me this means that a previous time, 'vagrant up' failed, and that 'vagrant destroy' did not remove the debris(!) left by the failed one.

**Comment by jukaradayi** [comment]
As @riebling said, it seems that the vagrant destroy did not do its job properly. 
Could you first open the virtualbox GUI and the virtual machine that should appear (it should be the only ones, if you don't have other virtual machine opened). 
Then, you could try launching the commands in the last post here:  https://github.com/hashicorp/vagrant/issues/6744
which seems to be the solution to a similar problem than the one you are having with Vagrant/VirtualBox on Windows. 

If that still doesn't work, could you destroy again the Virtual Machine (with the virtualbox GUI as previously), and then open the VagrantFile (as a text file, you can open it with the notepad) and add the line:
`      vbox.gui = true`
in the VagrantFile, at line 26, just below the line:
`      vbox.memory = 3072`
and above the line:
`    end`,
do `vagrant up` again, it should open a new window (the virtual machine) and you'll see the O.S. starting. It should get stuck as previously, so could you post here what is displayed in the window when the vagrant up is stuck ?

I hope this will help, don't hesitate if you want any precision on what I wrote. 

Julien

**Comment by yaklamtse** [comment]
I tried the commands but the ipconfig did not work:
![ipconfig](https://user-images.githubusercontent.com/37499299/37705280-c8a7826e-2cfb-11e8-81b8-ff5f64081076.PNG)

and sure whether resetting was succesfull, because after "resetting failed" it states "access denied" 
![netsh_error](https://user-images.githubusercontent.com/37499299/37705605-dee71f02-2cfc-11e8-943b-6eee0aa69a1a.PNG)

Moreover after the commands from the post I tried vagrant up and vagrant destroy, which resulted both in:
![vagrant_file](https://user-images.githubusercontent.com/37499299/37705693-318d75d0-2cfd-11e8-90f9-0a211fa398c9.PNG)

and changing the VagrantFile did not work either  :(

**Comment by jukaradayi** [comment]
Hi, 

The last picture you posted looks like an error in the VagrantFile.
Could you do a `git pull` in the DiViMe folder, followed by a `git checkout VagrantFile`, to make sure that you vagrant file is correct. 
Then try again with the vagrant up ? This now should at least give you another message than a "syntax error". 

Thank you ! 

Julien

**Comment by yaklamtse** [comment]
Hi,

It would not work on my Windows, so I have installed Ubuntu 16 and tried to install it there. It seems to be more progress, but not entirely yet. 
```
yaklam@yaklam-X550LD:~/DiViMe$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
    default: Adapter 3: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.2
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/yaklam/DiViMe
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
yaklam@yaklam-X550LD:~/DiViMe$ vagrant ssh -c "tools/test.sh"
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: /vagrant/MED_2s_100ms_htk.conf
(MSG) [2] in cComponentManager : successfully registered 95 component types.
(MSG) [2] in cComponentManager : successfully finished createInstances
                                 (19 component instances were finalised, 1 data memories were finalised)
(MSG) [2] in cComponentManager : starting single thread processing loop
(MSG) [2] in cComponentManager : Processing finished! System ran for 168 ticks.
Traceback (most recent call last):
  File "SSSF/code/predict/1-confidence-vm.py", line 11, in <module>
    import numpy
ImportError: No module named numpy
tools/test.sh: line 26:  echo: command not found
Noisemes passed the test...
Connection to 127.0.0.1 closed.

```
Thanks!

Yaklam

**Comment by riebling** [comment]
This is actually a sign of a working VM! It does the same thing for me. The error indicates there's a bug we've seen once before, regarding setting the user/login environment of commands run with "vagrant ssh -c": the interactive login environment doesn't get set, which causes one of the tests to fail (it does not find the anaconda environment to run Python correctly, running /usr/bin/python instead) - I forget the work-around. But a means to verify the VM tools self-test can pass, try running them as an interactive login:
```
vagrant ssh   # (logs you into the VM interactively)
tools/test.sh # run the tests
exit          # log out of the VM and return to the host
```

**Comment by riebling** [comment]
Not sure if you want to invest the time in trying again, but I believe to have corrected this behavior for the version of DiViMe found at https://github.com/srvk/DiViMe
Thanks for reporting it! (both tests were actually failing, and some of the error messages telling why were being suppressed)

**Comment by yaklamtse** [comment]
Hi!  
I tried it again with the new version of the DiViMe. Using vagrant destroy and then git pull and vagrant up again. However, when I want to run it over my WAV it report it cannot find it :(

I am sorry for the code. It could not get it to display under each other

`yaklam@yaklam-X550LD:~/DiViMe$ vagrant ssh -c "tools/test.sh"
(MSG) [2] in SMILExtract : openSMILE starting!
(MSG) [2] in SMILExtract : config file is: /vagrant/MED_2s_100ms_htk.conf
(MSG) [2] in cComponentManager : successfully registered 95 component types.
(MSG) [2] in cComponentManager : successfully finished createInstances
                                 (19 component instances were finalised, 1 data memories were finalised)
(MSG) [2] in cComponentManager : starting single thread processing loop
(MSG) [2] in cComponentManager : Processing finished! System ran for 168 ticks.
Traceback (most recent call last):
  File "SSSF/code/predict/1-confidence-vm.py", line 11, in <module>
    import numpy
ImportError: No module named numpy
tools/test.sh: line 26:  echo: command not found
Noisemes passed the test...
Connection to 127.0.0.1 closed.
yaklam@yaklam-X550LD:~/DiViMe$ ssh -c "tools/ldc_sad.sh data/"
Unknown cipher type 'tools/ldc_sad.sh data/'
yaklam@yaklam-X550LD:~/DiViMe$ vagrant ssh -c "tools/ldc_sad.sh data/"
folder is not empty!
ls: cannot access /vagrant/data/*.wav: No such file or directory
Tests finished
tools/ldc_sad.sh: line 26: cd: /home/vagrant/ldc_sad_hmm: No such file or directory
using ldc_sad_hmm to perform Speech Activity Detecton
/home/vagrant/anaconda/bin/python: can't open file 'perform_sad.py': [Errno 2] No such file or directory
finished using ldc_sad_hmm. Please look inside data/ to see the output in *.rttm format
ls: cannot access /vagrant/data//*.wav: No such file or directory
Connection to 127.0.0.1 closed.
`
`
`
`

**Comment by riebling** [comment]
Looks like the same problem where Python virtual environment numpy was not being used.
Then, it appears the shared folder /vagrant is not found.
Actually looking at the output you pasted, this might be from the same, old VM, and not the one at https://github.com/srvk/diarizationVM
That one prints different messages when running tools/test.sh:
```
er1k@islpc22:/tmp/DiViMe$ vagrant ssh -c "tools/test.sh"
Testing noisemes...
Noisemes passed the test.
Testing DIARTK...
DiarTK passed the test.
Congratulations, everything is OK!
Connection to 127.0.0.1 closed.
```

**Comment by yaklamtse** [comment]
Hi I destroyed the VM and then used `$ git clone https://github.com/srvk/DiViMe` instead of `github.com/aclew/DiViMe` However this resulted in:
```
yaklam@yaklam-X550LD:~/DiViMe$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'vbguest'.
```

I retried it with `github.com/aclew/DiViMe` after destroying the VM as well, but that resulted in the same output as my post earlier

**Comment by riebling** [comment]
Good catch! I have the vbguest plugin installed in my Vagrant to manage VirtualBox guest additions. That directive was there to turn off the automatic updating of VB guest additions but throws an error if the plugin isn't installed.

I'll remove that from the Vagrantfile, thanks for catching it.

**Comment by yaklamtse** [comment]
`Testing noisemes...
Noisemes passed the test.
Testing DIARTK...
DiarTK passed the test.
Congratulations, everything is OK!
Connection to 127.0.0.1 closed.
`
it's working! Thanks so much for the help! :)

**Comment by riebling** [comment]
Yay! You're welcome. yes, at one point the tests themselves were broken, and didn't correctly report results, which is what prompted the change in output showing before/after each test. Based on this I'll go ahead and close this Issue
