### ISSUE TITLE
/vagrant/hyp not found in noisemes_full.sh

### ISSUE THREAD

**Issue by sliaqat1** [aclew/DiViMe#10]
In the tools/noisemes_full.sh file, there's a for loop iterating over the /vagrant/hyp directory. That directory didn't exist, but when I changed the directory to hyp_sum, which did exist in /vagrant/, it worked. I'm not sure if this is a robust fix, but it worked in my case.

**Comment by riebling** [comment]
We're no longer explicitly supporting noisemes_full (but may include it as an undocumented 'extra' in utils/ for future use? )
So this can be closed
