### ISSUE TITLE
score.py not found in evalSAD.sh

### ISSUE THREAD

**Issue by sliaqat1** [aclew/DiViMe#12]
When running the evalSAD.sh script, I got the error stating score.py was not found. I went into the directory that the script goes into into and found it was empty. I looked for the score.py file and found it in the dscore directory in home. That's when I noticed that evalSAD.sh script had commented out lines to cd into dscore instead of ldc_sad_hmm. I was confused on if this was intentional, since I don't understand the purpose of the ldc_sad_hmm directory.

**Comment by riebling** [comment]
This confusion makes sense actually: ldc_sad_hmm and dscore both have score.py scripts; these are different scripts that HAPPEN to have the same name, but work differently!
I think this might also explain what happened in #13 

Now we have a different evalSad.sh script, and I believe this error should no longer happen; assuming a VM is provisioned and gets dscore/ tool installed (which we'll know by whether or not test.sh gives a success message) we can probably claim this to be resolved
