### ISSUE TITLE
Error in score.py when running evalSAD.sh script.

### ISSUE THREAD

**Issue by sliaqat1** [aclew/DiViMe#13]
I ran the evalSAD.sh script after changing the directory from ldc_sad_hmm to dscore. On every file that was run, I got the error:

Traceback (most recent call last):
  File "score.py", line 78, in <module>
    args.ignore_overlaps, args.step)
  File "/home/vagrant/dscore/scorelib/score.py", line 255, in score
    der = metrics.der(ref_rttm_fn, sys_rttm_fn, collar=collar)
  File "/home/vagrant/dscore/scorelib/metrics.py", line 282, in der
    txt = subprocess.check_output(cmd, stderr=f)
  File "/home/vagrant/anaconda/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'/home/vagrant/dscore/scorelib/md-eval-22.pl', u'-r', '/vagrant/data/temp_ref', u'-s', '/vagrant/data/temp_sys/audio_1480294656271.lab', u'-c', '0.25', u'-1']' returned non-zero exit status 25

I ran the test script and it confirmed that installation was done correctly. The evalSAD was being run on wav files with rttm labels.

**Comment by riebling** [comment]
This confusion makes sense actually: ldc_sad_hmm and dscore both have score.py scripts; these are different scripts that HAPPEN to have the same name, but work differently!
I think this might also explain what happened in #12 

Now we have a different evalSad.sh script, and I believe this error should no longer happen; assuming a VM is provisioned and gets dscore/ tool installed (which we'll know by whether or not test.sh gives a success message) we can probably claim this to be resolved
