### ISSUE TITLE
Missing files in installation?

### ISSUE THREAD

**Issue by chloepouprom** [aclew/DiViMe#3]
Hi, when I run the test script, I get the following output:
```➜  DiViMe git:(master) ✗ vagrant ssh -c "tools/test.sh"
tools/test.sh: line 18: cd: /home/vagrant/ldc_sad_hmm: No such file or directory
tools/test.sh: line 19:  exit: command not found
grep: /vagrant/test2.lab: No such file or directory
LDC_SAD passed the test...
tools/test.sh: line 26:  exit: command not found
Noisemes passed the test...
tools/test.sh: line 34: 1: command not found
Connection to 127.0.0.1 closed.
```

Thanks!

**Comment by riebling** [comment]
Funny, I get the same type of errors. It seems we were instructed to remove the ldc_sad_hmm tool, and so the repository is gone (not allowed to distribute it - yet) but the Vagrant provisioning file was not updated to reflect this.

As a result, we cannot run the scoring, and the selftest fails.

The rest of the VM should probably function OK, just nothing that uses ldc_sad_hmm scoring. This is planned to be added back once it's allowed to be distributed / referenced by us.

**Comment by chloepouprom** [comment]
Good to know! Thanks @riebling
